:imagesdir: ./images
:source-highlighter: rouge
:icons: font

= KSQL & Kafka Streams Exercises
Sample Solutions - Version 5.0.0-v1

== Cloning the Repository

. Clone this repository into a folder `~/confluent-labs` on your computer:

    $ git clone https://github.com/confluentinc/training-ksql-and-streams-src.git ~/confluent-streams

. Navigate to this folder:

    $ cd ~/confluent-streams

. *Optional:* Open this folder in your favorite code editor; e.g. if you have *VS Code* installed then:

    $ code .

NOTE: We have two main folders `solution` and `labs` in this repo. The former contains the complete sample solution for each exercise while the latter contains the scaffolding for each exercise and is meant to be used during the hands-on-labs. +
For each module of the course that has exercises we have a corresponding sub-folder `m-xx` where the respective exercises can be found.

== Java base Exercises using Gradle

To build a project Java project using *Gradle* do the following:

1. `cd` into the corresponding project folder (the folder where the *Gradle* build file `build.gradle` is located).

2. Run this command to build the `jar`:
+
[source,subs="verbatim,quotes"]
----
$ *docker container run --rm \
    -v ${PWD}:/home/gradle/project \
    -v ${HOME}/.gradle:/root/.gradle \
    -w /home/gradle/project \
    frekele/gradle:latest gradle build*
----

3. Run the application:
+
----
$ docker container run --rm \
    -v $(PWD)/target/app.jar:/app.jar \
    openjdk:8-jre-alpine java -jar /app.jar
----
+
NOTE: Sometimes the Alpine based image is not working depending on the dependencies used. In this case use this  command instead:
+
----
$ docker container run --rm \
    -v $(PWD)/target/app.jar:/app.jar \
    openjdk:8-jre java -jar /app.jar
----
